# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: fanout-pattern

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

package:
  individually: true
  # exclude:
  #   - ./**
  #   - layers/**
  patterns:
    - "!./*"
    - src/**
    - "!node_modules/**"

layers:
  NodeModules:
    path: layers/node-layer
    compatibleRuntimes:
      - nodejs18.x

custom:
  settings:
    ORDER_DYNAMODB_TABLE: orders

plugins:
  - serverless-iam-roles-per-function

functions:
  hello:
    handler: src/order-acknowledgement.handler
    package:
      patterns:
        - src/order-acknowledgement.js
    layers:
      - !Ref NodeModulesLambdaLayer
    events:
      - http:
          path: /orders/acknowledgement
          method: post
          cors: true

resources:
  Resources:
    orders:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.settings.ORDER_DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "status"
            AttributeType: "S"
          - AttributeName: "created_at"
            AttributeType: "S"
          - AttributeName: "type"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "type"
            KeyType: "RANGE"
        GlobalSecondaryIndexes:
          - IndexName: status-date-index
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              NonKeyAttributes: []
              ProjectionType: ALL
        BillingMode: "PAY_PER_REQUEST"
        Tags:
          - Key: "Name"
            Value: ${self:custom.settings.ORDER_DYNAMODB_TABLE}
