Resources:
  FanoutSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "FanoutTopic"

  NotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref FanoutSNSTopic
      Endpoint: ${construct:notification-queue.queueArn}
      Protocol: sqs
      RawMessageDelivery: true

  DigitalOrderProcessingSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref FanoutSNSTopic
      Endpoint: ${construct:digital-order-processing-queue.queueArn}
      Protocol: sqs
      RawMessageDelivery: true
      FilterPolicy:
        orderType:
          - digital

  OrderShipmentSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref FanoutSNSTopic
      Endpoint: ${construct:order-shipment-queue.queueArn}
      Protocol: sqs
      RawMessageDelivery: true
      FilterPolicy:
        orderType:
          - physical

  NotificationSubscriberQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - ${construct:notification-queue.queueUrl}
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - "SQS:SendMessage"
            Resource: ${construct:notification-queue.queueArn}

  OrderShipmentSubscriberQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - ${construct:order-shipment-queue.queueUrl}
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - "SQS:SendMessage"
            Resource: ${construct:order-shipment-queue.queueArn}

  DigitalOrderSubscriberQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - ${construct:digital-order-processing-queue.queueUrl}
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - "SQS:SendMessage"
            Resource: ${construct:digital-order-processing-queue.queueArn}
